# Generated by Django 4.2.7 on 2023-11-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='fee_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_app.customers'),
        ),
    ]
